</section>
			<footer>
				<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/es/">
				<img alt="Licencia de Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/3.0/es/88x31.png" /></a>
				<br />Este obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/es/">licencia de Creative Commons Reconocimiento-NoComercial-CompartirIgual 3.0 España</a>.
			</footer>
		</div>
	</body>
</html>
