<?php
session_start();
if(!isset($_SESSION['contador'])){$_SESSION['contador'] = 0;}
?>
<!doctype html>
<html lang="es">
	<head>
		<title>Tienda</title>
		<link rel=Stylesheet href="../estiloadmin1.css" >
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		
	</head>
	<body>
		<div id="contenedor">
			<header>
				<a href="../index.php"><h1>Panel de control</h1></a>
				
			</header>
			<section>
			
			
